Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#!/usr/bin/python3

import sys

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

import numpy
from numpy.random import randn
from scipy import array, newaxis


input1=[10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,
        10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,
        10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,]
input2=[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,
        2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,
        6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0]
output=[10.0,20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,
        5.0,10.0,15.0,20.0,25.0,30.0,35.0,40.0,45.0,50.0, 
       1.6666833333333333, 3.3333666666666666, 5.00005, 6.666733333333333, 8.333416666666666, 10.0001, 11.666783333333331, 13.333466666666666, 15.00015, 16.666833333333333]

points = [[0,0,0] for i in range(len(output))]

for i in range(len(output)):
    points[i] = [input1[i],input2[i],output[i]]

DATA = numpy.array(points)

Xs = DATA[:,0]
Ys = DATA[:,1]
Zs = DATA[:,2]

#print(DATA)

# Creating figure
fig = plt.figure(figsize = (5, 5))
ax = plt.axes(projection ="3d")
 
# Creating plot
ax.scatter3D(Xs, Ys, Zs, color = "green")
plt.title("simple 3D scatter plot")
 
# show plot
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[10], line 13[0m
[1;32m     11[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumpy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrandom[39;00m [38;5;28;01mimport[39;00m randn
[0;32m---> 13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m array, newaxis
[1;32m     16[0m input1[38;5;241m=[39m[[38;5;241m10.0[39m,[38;5;241m20.0[39m,[38;5;241m30.0[39m,[38;5;241m40.0[39m,[38;5;241m50.0[39m,[38;5;241m60.0[39m,[38;5;241m70.0[39m,[38;5;241m80.0[39m,[38;5;241m90.0[39m,[38;5;241m100.0[39m,
[1;32m     17[0m         [38;5;241m10.0[39m,[38;5;241m20.0[39m,[38;5;241m30.0[39m,[38;5;241m40.0[39m,[38;5;241m50.0[39m,[38;5;241m60.0[39m,[38;5;241m70.0[39m,[38;5;241m80.0[39m,[38;5;241m90.0[39m,[38;5;241m100.0[39m,
[1;32m     18[0m         [38;5;241m10.0[39m,[38;5;241m20.0[39m,[38;5;241m30.0[39m,[38;5;241m40.0[39m,[38;5;241m50.0[39m,[38;5;241m60.0[39m,[38;5;241m70.0[39m,[38;5;241m80.0[39m,[38;5;241m90.0[39m,[38;5;241m100.0[39m,]
[1;32m     19[0m input2[38;5;241m=[39m[[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,[38;5;241m1.0[39m,
[1;32m     20[0m         [38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,[38;5;241m2.0[39m,
[1;32m     21[0m         [38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m,[38;5;241m6.0[39m]

[0;31mImportError[0m: cannot import name 'array' from 'scipy' (/opt/jupyterhub/lib/python3.10/site-packages/scipy/__init__.py)

